### ISSUE TITLE
missing pip install requirements and a specific requirement

### ISSUE THREAD

**Issue by sofiapinto** [nestauk/dap_tutorials#11]
hey @india-kerle ,
So besides missing the `pip install -r llm_requirements.txt` from the langchain tutorial, I think we also missed `typing-extensions` from the requirements. At least I had to install it.

**Comment by sofiapinto** [comment]
and thanks so much again for the amazing tutorial!!! ❤️⭐️

**Comment by india-kerle** [comment]
thank you!! I've just added 👍
